config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "selenium#specs"

  resources :jobs

  get "selenium/specs"
  post "selenium/run"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	
	def index
	end

	def show
	end

	def create
		job_id 
		Job.create(:guid => params.keys[0], )
	end

end

app/controllers/selenium_controller.rb
class SeleniumController < ApplicationController

	def specs
		response = HTTParty.get("#{ALLEYWAY_CONFIG["url"]}/selenium/specs")
		@specs = JSON.parse(response.body)
	end

	def run
		body = {
			:selenium => {
				:job_guid => SecureRandom.uuid,
				:spec => params[:specs],
				:environment => params[:environment],
				:browser => params[:browser]
			}
		}

		response = HTTParty.post("#{ALLEYWAY_CONFIG["url"]}/selenium/run", 
			:body => body.to_json,
			:headers => { 'Content-Type' => 'application/json' })

		redirect_to root_path
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/selenium_helper.rb
module SeleniumHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frontage2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'shared/navbar' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
  </body>
</html>

app/views/selenium/specs.html.erb
<div class="container">
	<%= form_tag("/selenium/run") do %>
		<div class="row form-group">
			<%= select_tag "browser", options_for_select([ "chrome", "firefox" ]), :class => "col form-control" %>
			<%= select_tag "environment", options_for_select([ "sand", "qa", "int", "prod"]), :class => "col form-control" %>
		</div>

		<% @specs.keys.each do |feature| %>
			<div class="feature">
				<div class="row">
					<h1><%= feature %></h1>
				</div>
				<% @specs[feature].keys.each do |spec| %>
					<div class="form-check">
						<label class="form-check-label">
							<%= check_box_tag 'specs[]', @specs[feature][spec]["command"], false, :class => "form-check-input" %>
							<%= spec %> - <%= @specs[feature][spec]["description"] %>
						</label>
					</div>
				<% end %>
			</div>
		<% end %>
		<%= submit_tag "Run", :class => "btn btn-primary"%>

	<% end %>    
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-dark bg-faded">
	<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContet" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<%= link_to "Frontage", root_path, :class => "navbar-brand" %>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<%= link_to "Run", selenium_specs_path, :class => "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to "Jobs", jobs_path, :class => "nav-link" %>
			</li>
		</ul>
	</div>
</nav>